In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
from numpy import mean
from numpy import std
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
from BaselineRemoval import BaselineRemoval
from sklearn.model_selection import KFold, cross_val_score
from sklearn.svm import SVC
from sklearn.metrics import classification_report

plt.rcParams["figure.figsize"] = [7.50, 3.50]
plt.rcParams["figure.autolayout"] = True

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

In [13]:
ages_df = pd.read_csv("AGEs.csv")
arm_df = pd.read_csv("original_raman_spectroscopy/innerArm.csv")
thumbnail_df = pd.read_csv("original_raman_spectroscopy/thumbNail.csv")
earlobe_df = pd.read_csv("original_raman_spectroscopy/earLobe.csv")
vein_df = pd.read_csv("original_raman_spectroscopy/vein.csv")

In [ ]:
def polyFit(df):
    polynomial = 5
    gradient = 0.05
    df
    return df

In [16]:
def crop_range_to_numpy(df):
    
    # Dropping columns : ['patientID', 'has_DM2']
    df_dropped_index = df.drop(labels=['patientID', 'has_DM2'], axis=1, inplace=False)
    
    # Cropping raman shift from range 800 cm-1 to 1800cm-1
    cropped_signal = df_dropped_index.loc[:, 'Var802':'Var1801']
    
    # Convert data to numpy.ndarray
    cropped_signal_np = cropped_signal.to_numpy()
    
    # Dropping the first index corresponding to label : ramanShift
    cropped_signal_np = cropped_signal_np[1:]
    
    return cropped_signal_np

In [14]:
ages_df

,AGEsID,Var802,Var803,Var804,Var805,Var806,Var807,Var808,Var809,Var810,...,Var1793,Var1794,Var1795,Var1796,Var1797,Var1798,Var1799,Var1800,Var1801,Var1802
0,ramanShift,800.000000,801.000000,802.000000,803.000000,804.000000,805.000000,806.000000,807.000000,808.000000,...,1791.000000,1792.000000,1793.000000,1794.000000,1795.000000,1796.000000,1797.000000,1798.000000,1799.000000,1800.000000
1,3-deoxyglucosone,0.001791,0.001813,0.001839,0.001868,0.001899,0.001929,0.001956,0.001980,0.002002,...,0.000492,0.000492,0.000495,0.000502,0.000509,0.000516,0.000524,0.000534,0.000543,0.000553
2,glyoxal,0.000220,0.000243,0.000270,0.000299,0.000331,0.000367,0.000405,0.000445,0.000488,...,0.000213,0.000217,0.000222,0.000227,0.000233,0.000240,0.000247,0.000253,0.000256,0.000256
3,GOLD,0.000302,0.000295,0.000288,0.000281,0.000275,0.000268,0.000262,0.000256,0.000251,...,0.000141,0.000142,0.000142,0.000129,0.000128,0.000128,0.000127,0.000127,0.000126,0.000126
4,methylglyoxal,0.003002,0.003058,0.003095,0.003115,0.003121,0.003115,0.003098,0.003072,0.003038,...,-0.000115,-0.000130,-0.000146,-0.000161,-0.000176,-0.000190,-0.000205,-0.000219,-0.000223,-0.000224
5,MG-H2,0.000236,0.000231,0.000226,0.000221,0.000215,0.000208,0.000202,0.000195,0.000187,...,0.000034,0.000049,0.000065,0.000082,0.000101,0.000122,0.000144,0.000168,0.000194,0.000192
6,pentosidine,0.000803,0.000748,0.000693,0.000637,0.000582,0.000527,0.000475,0.000424,0.000377,...,0.000069,0.000067,0.000065,0.000063,0.000060,0.000092,0.000092,0.000092,0.000092,0.000092

In [25]:
X = crop_range_to_numpy(vein_df)
y = arm_df['has_DM2'].drop(0, inplace=False)

In [26]:
print(X)
print('\n')
print('The shape of cubital vein dataset is ', X.shape)

[[191.2475708  195.5560272  198.0248413  ...  59.15124054  63.82999878
   65.05268784]
 [262.1858643  266.9431122  271.2298065  ...  91.87278899  90.74000244
   88.29462433]
 [180.2089203  181.0167572  182.0608642  ...  60.97762298  63.40801468
   55.58280182]
 ...
 [282.5561218  284.6205933  286.8745239  ... 101.6480621  108.5540176
   98.52796326]
 [585.4418204  590.9556318  594.1446272  ... 225.6394087  222.9635729
  221.4788796 ]
 [240.7701238  245.1085027  249.0548528  ...  85.07067298  85.62666956
   83.99641737]]


The shape of cubital vein dataset is  (20, 1000)

In [64]:
print(X)
print(f'The shape of X is : {X.shape}')

[[345.8314642  350.6934332  351.9772339  ... 107.9693807  113.2883358
  111.4543031 ]
 [232.1680176  235.3096008  240.2931427  ...  76.33356629  72.39400024
   72.14946137]
 [482.391803   487.6876221  490.1527954  ... 160.3856354  164.080011
  159.1892487 ]
 ...
 [133.321551   137.2859294  139.4813639  ...  40.94071897  46.81751378
   39.37948608]
 [301.1747081  306.9342702  309.3126323  ... 111.7359607  107.1366704
  105.9139811 ]
 [170.328982   174.9665553  179.3695526  ...  57.2306633   56.78333728
   54.74552091]]
The shape of X is : (20, 1000)

In [65]:
print(y)
print(f'The shape of X is : {y.shape}')

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
The shape of X is : (20,)

In [69]:
kf = KFold(n_splits=10, shuffle=True, random_state=4)

for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

TRAIN: [ 0  1  2  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18] TEST: [ 3 19]
TRAIN: [ 0  1  2  3  4  5  7  8  9 10 11 12 13 14 15 16 17 19] TEST: [ 6 18]
TRAIN: [ 0  1  2  3  5  6  7  8  9 10 11 12 14 15 16 17 18 19] TEST: [ 4 13]
TRAIN: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 18 19] TEST: [ 0 17]
TRAIN: [ 0  1  2  3  4  5  6  7  8  9 10 13 14 15 16 17 18 19] TEST: [11 12]
TRAIN: [ 0  1  2  3  4  5  6  7  8  9 11 12 13 14 16 17 18 19] TEST: [10 15]
TRAIN: [ 0  1  3  4  5  6  7  8 10 11 12 13 14 15 16 17 18 19] TEST: [2 9]
TRAIN: [ 0  1  2  3  4  5  6  8  9 10 11 12 13 14 15 17 18 19] TEST: [ 7 16]
TRAIN: [ 0  2  3  4  5  6  7  9 10 11 12 13 14 15 16 17 18 19] TEST: [1 8]
TRAIN: [ 0  1  2  3  4  6  7  8  9 10 11 12 13 15 16 17 18 19] TEST: [ 5 14]

In [78]:
model = SVC()

scores = cross_val_score(model, X, y, scoring='accuracy', cv=kf, n_jobs=-1)

In [79]:
print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))

Accuracy: 0.450 (0.150)